server 
{
    listen 8080;
    server_name localhost;

    root /var/www/html;
    index index.html;

    client_max_body_size 1000000;

    error_page 404 /errors/404.html;
    error_page 500 /errors/500.html;

    location / {
        root ./www;
        index index.html;
        autoindex on;
        allow_methods GET POST DELETE;
    }
    location /index {
        root ./www;
        index karim.html;
        autoindex off;
        allow_methods GET POST DELETE;
    }
 
    location /images {
        root ./www;
        # index index.php`;
        autoindex off;
        allow_methods GET POST;
    }

    


    # location /old_page {
    #     return 301 http://localhost/new_page;
    # }
}
